### PR TITLE
Switch to using LTS 13.26

### PR DESCRIPTION
**Pull request by etherz10**
@adinapoli When you got some time could you possibly review this patch and release this version to Hackage?

Hope you're doing well! 🍰

### CODE REVIEW

**Comment by Mikolaj** [comment]
This probably restricts the package to newest GHCs, but if we are the only users, that's fine. If not and other users create tickets, we can ifdef the changes.

**Comment by adinapoli** [comment]
Hey all! Nice to hear from you.

At the moment I am away for the weekend as I am on a business trip. Can
this wait until next week?

I think I agree with Mikolaj here: there might be other people who depend
on the library, but if they open a ticket we can ifdef the changes.

I think this will be fine though: considering where the Haskell ecosystem
is going these days, I am not expecting too many people on older GHCs :)

A.

**Review by adinapoli — APPROVED** [review]

**Comment by adinapoli** [comment]
@etherz10 Merged! As I am running out of time, I have simply given @Mikolaj contribution access to the package on Hackage, so that he can proceed to upload this (and future) revision(s) himself :)

http://hackage.haskell.org/package/snaplet-purescript/maintainers/

Hope it helps!

**Comment by Mikolaj** [comment]
Thank you, Alfredo. Great job with the patch, Kieron. Yes, I'll gladly upload your work.

**Comment by Mikolaj** [comment]
Uh, the package compiles fine, but when I'm trying to upload, I'm getting 

```
Invalid package

'ghc-options: -Wall -Werror' makes the package very easy to break with future GHC versions because new GHC versions often add new warnings. Use just 'ghc-options: -Wall' instead. Alternatively, if you want to use this, make it conditional based on a Cabal configuration flag (with 'manual: True' and 'default: False') and enable that flag during development.
```

For now I will just remove `-Werror` from the package archive instead of touching the repo. Next time that we propose a PR, we may try to sneak in the fix as well. The candidate, thus perturbed, is at

http://hackage.haskell.org/package/snaplet-purescript-0.5.2.3/candidate

Will publish this evening.

**Comment by Mikolaj** [comment]
Published. Matrix builds (8.6.5 and 8.4.4) are fine. Docs, too. Well done. :)

**Comment by etherz10** [comment]
Thanks guys! 🎈

**Pull request merged**
